### ISSUE TITLE
Can't catch r\connect()

### ISSUE THREAD

**Issue by grantwork** [danielmewes/php-rql#102]
This may just be a lack of PHP experience on my end, but I just can't catch the r\connect function to fail gracefully in my app. I've searched the code and I can't see any other catch/try that would run over mine. This is what I'm trying to use.

```php
try {
	$conn = r\connect(RDB_HOST, RDB_PORT, '', RDB_AUTH, 5);
} catch (\MyException $e) {
    Airbrake\Instance::notify($e);
}
```

Any ideas why I can't catch the connect error?

**Comment by mbrevda** [comment]
That's because no exception is thrown. If you want to "catch" a connection error, look into creating an error handler, and catch the socket error.

**Comment by danielmewes** [comment]
@grantwork The exception type that `r\connect` throws is `r\RqlDriverError`. You can catch it like this:
```php
try {
    $conn = r\connect(RDB_HOST, RDB_PORT, '', RDB_AUTH, 5);
} catch (r\RqlDriverError $e) {
    ...
}
```

**Comment by danielmewes** [comment]
@mbrevda `r\connect` actually does check for connection errors and throws an `r\RqlDriverError` if the connection setup fails.

**Comment by grantwork** [comment]
@danielmewes Using your `r\RqlDriverError` worked great. I was trying to use mine which obviously wasn't working. Thanks.

**Comment by mbrevda** [comment]
My bad! I was confusing certain scenarios where phpunit will stop execution as soon as the warning is hit.
