### ISSUE TITLE
indexCreate should allow skipping the index function but still having the options

### ISSUE THREAD

**Issue by danielmewes** [danielmewes/php-rql#110]

**Comment by mbrevda** [comment]
What would the index be in that case?

**Comment by danielmewes** [comment]
The server will generate a function from the index name: `function($x) { return $x('indexName'); }`

**Comment by danielmewes** [comment]
(to clarify: you can currently do `indexCreate(name, function, ["multi" => true])` or `indexCreate(name)`, but not `indexCreate(name, ["multi" => true])` in PHP-RQL)

**Comment by danielmewes** [comment]
Arg, turns out this is already possible. `indexCreate` actually doesn't take options. Instead `indexCreateMulti` must be used.
