### ISSUE TITLE
Compound Indexes

### ISSUE THREAD

**Issue by rclations** [danielmewes/php-rql#120]
Are compound indexes supported?
https://rethinkdb.com/docs/secondary-indexes/javascript/

I assumed if the standard getAll was
`r\table('marvel')->getAll('man_of_steel', array('index' =>'code_name'))->run($conn)`
then a compound index would work like
`r\table('marvel')->getAll(array('dark_night', 'man_of_steel'), array('index' =>'code_name'))->run($conn)`

but it doesn't appear to be working

**Comment by rclations** [comment]
nvm, works great!

**Comment by danielmewes** [comment]
Yes compound indexes are supported. How did you create the index?

**Comment by danielmewes** [comment]
Ah :-)
