### ISSUE TITLE
any info about changes() support?

### ISSUE THREAD

**Issue by boynet** [danielmewes/php-rql#129]
how this is working?
```
$feed = r\table('games')->changes()->run($conn);
foreach ($feed as $change) {
  print_r($change);
}
```
is it gonna keep the php script run forever?

**Comment by danielmewes** [comment]
@boynet Yes, currently the PHP driver is completely synchronous, so you can't have multiple operations at the same time.

If your version of PHP supports it, you can use multi-threading to open multiple RethinkDB connections and perform different tasks on each thread.
