### ISSUE TITLE
hasFields with not()

### ISSUE THREAD

**Issue by nanoKwant** [danielmewes/php-rql#141]
Hi Daniel,

Thanks for your driver !
But I have a specific request to add to my code : 

RQL ->
`r.db("myDB").table("myTable").filter(r.row.hasFields('myField').not())`

I try (but it doesn't work) ->
`r\table($myTable)->filter(r\row->hasFields($myField))->not()`

Thanks for your help !

**Comment by Geekimo** [comment]
The .not should be on the .hasFields, not on .filter

**Comment by nanoKwant** [comment]
It doesn't work too

`r\table($myTable)->filter(r\row->hasFields($myField)->not())`

**Comment by Geekimo** [comment]
What is the result of `r\table($myTable)->filter(r\row->hasFields($myField)->not())` ?
Do you get all the table rows or nothing ?

**Comment by nanoKwant** [comment]
`PHP Parse error:  syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ')'`

**Comment by danielmewes** [comment]
`r\row` must also be called as a function: `r\row()`

**Comment by nanoKwant** [comment]
Perfect, it works, thanks !!
`r\table($myTable)->filter(r\row()->hasFields($myField)->not())`
