### ISSUE TITLE
Realtime app

### ISSUE THREAD

**Issue by aolko** [danielmewes/php-rql#143]
Is it possible to make realtime app w/ php-rql? (see notifications,chat,etc.)
**No node.js please, thanks**

**Comment by Geekimo** [comment]
changes has not been implemented yet, but you can do realtime apps using php, even if this is not the main purpose of php.

**Comment by aolko** [comment]
any examples (like chat or notifications) or tutorials?

**Comment by RoySegall** [comment]
You can have a look on how I connected Drupal and RethinkDB using Pusher as the WebSocket service.

when there is a new record I'm [pushing](https://github.com/RoySegall/rethinkdb/blob/8.x-1.x/modules/rethinkdb_replica/rethinkdb_replica.module#L21) it to RethinkDB. Then NodeJS [listen](https://github.com/RoySegall/rethinkdb/blob/8.x-1.x/modules/rethinkdb_websocket/nodejs/index.js) to any changes from RethinkDB and send it to Pusher. 
The last thing is to connect the [front end](https://github.com/RoySegall/rethinkdb/blob/8.x-1.x/modules/rethinkdb_websocket/js/activity_stream.js#L26-L33) to Pusher and wait for updates - one I have it I'm appending it to a div and that's it.

**Comment by aolko** [comment]
well, that's good and all, **_BUT_** **pusher is a freemium service** which won't do in my case, **only free/open-source**, as for node.js see the bold sentence in my first post ;)
p.s. I also have to communicate w/ mariadb

**Comment by RoySegall** [comment]
Well... You can use socket io in this case if you'd like to. Pusher is just another service in the tool box.

You can also have a look on those two gents - http://reactphp.org/, http://socketo.me/

**Comment by danielmewes** [comment]
Closing because this is not an actionable issue as it stands. @RoySegall provided some pointers about frameworks that could be used for future integration of the driver.
