### ISSUE TITLE
Nested map error.

### ISSUE THREAD

**Issue by wojons** [danielmewes/php-rql#49]
When running a groupedMapReduce in javascript there is lexicon variable scoping so the variables above are aviable so i can then have an inner map to use as a loop.

```
doc("rawr").keys().map(function(doc2) {
return [doc2, doc("rawr")(doc2)]
}).corecTo("object")
```

When i try it in php the doc var is NULL

**Comment by billbarsch** [comment]
hahahah when I found the solution his name is daniel mewes!!!

*****************THIS NOT WORKS---->>>***********************
function xxx(){
$my_search = "adfasdfa";
$return = r\table("tablename")->filter(function($row){
return $row("keyname")->eq($my_serach);
})->run($conn);


*****************THIS WORKS!!!!!---->>>>***********************
function xxx(){
$my_search = "adfasdfa";
$return = r\table("tablename")->filter(function($row) USE ($my_serach){
return $row("keyname")->eq($my_serach);
})->run($conn);

God bless you Daniel!!!! hehehe
