### ISSUE TITLE
changes() doesn't work with ->filter()

### ISSUE THREAD

**Issue by sandeepshetty** [danielmewes/php-rql#73]
This works:

``` php
r\table("some_table")->changes()->run($conn);
foreach ($cur as $elem) { var_dump($elem->toNative()); }
```

This doesn't:

``` php
r\table("some_table")->changes()->filter(r\row('foo')->eq('bar'))->run($conn);
foreach ($cur as $elem) { var_dump($elem->toNative()); }
```

**Comment by nikhil102** [comment]
can any one tell me how change function work beause it not working for me at list it showing blank result array() when i use change function 

code for insert

  $document = array('user1' => $rand);
    $result =  r\db("talklaw")->table("tablePhpTest")->insert($document)
        ->run($conn);

code for view
 
 
$feed = r\table('tablePhpTest')->changes()->run($conn);
		echo "<pre>";
		print_r($feed);
		 exit();
