### ISSUE TITLE
empty object error datum to native

### ISSUE THREAD

**Issue by wojons** [danielmewes/php-rql#77]
https://github.com/danielmewes/php-rql/blob/c4ebfe919d818fff43fad1be1b3a7fa6dd13d05d/src/rdb/datum.php#L370

So i cam across a bug. The value leaves the db as an empty object and php writes it as an empty array and then fills it with data. But in the case that the data is just an empty object then its a php array. and when the user then json encodes the data again. they end up sending an empty array and not an empty object. And PHP uses different syntax for array and objects

**Comment by wojons** [comment]
Look at this.

http://php.net/manual/en/class.arrayobject.php In the "short" tests i did it should work

```
native = new ArrayObject();
```

**Comment by wojons** [comment]
I would submit a pull request but we both know my fork is better (i really need to diff them and go back to yours)

https://github.com/wojons/PHP-ReQL/commit/2aa0ec0a700fd43cca1001c449a190c1c254629b

**Comment by danielmewes** [comment]
Talked to @wojons . The key here is to make `toNative()` generate `ArrayObject` objects rather than associative arrays. That way we can always distinguish arrays from object when converting back to a ReQL datum, which avoids this issue.

Since that change could in rare cases break code that uses PHP-RQL, I will apply it for the 2.0 release but not before.

**Comment by danielmewes** [comment]
I think this might actually allow us to get rid of `toNative()` completely. Instead the conversion would be performed automatically, since it wouldn't involve information loss anymore. I'll think about that a bit.
That would definitely be a 2.0 change.

**Comment by danielmewes** [comment]
Implemented this in branch v2.0, commit https://github.com/danielmewes/php-rql/commit/add8c03a7826af168bd1db72f1356af2f1a5eccc

Starting with PHP-RQL 2.0, `toNative()` is no longer necessary. Instead run() and cursors will return native objects directly (similar to the official drivers).
Objects will be returned as `ArrayObject`s as @wojons suggested.
