### ISSUE TITLE
literal requires arg

### ISSUE THREAD

**Issue by archaicowl** [danielmewes/php-rql#79]
Setup (in rethinkdb web data explorer):
```
    r.dbCreate('bug_report');
    r.db('bug_report').tableCreate('literal', {'primaryKey':'name'});
    r.db('bug_report').table('literal').insert({
      'name':'bubba',
      'type':'dog',
      'attributes':{
      	'colors':{
      		'red':1,
    			'white':1, 
    			'blue':0
      	}
      }
    });
    r.db('bug_report').table('literal').insert({
      'name':'fluffy',
      'type':'cat',
      'attributes':{
      	'colors':{
      		'red':0,
    			'white':1, 
    			'blue':1
      	}
      }
    });
    r.db('bug_report').table('literal');
```
Example (in rethinkdb web data explorer):
```
    r.db('bug_report').table('literal').get('fluffy').update({'attributes':{'colors':{'white':r.literal()}}});
    r.db('bug_report').table('literal');
```

Example (called using php literal.php):
```
<?php

require('rdb/rdb.php');
$conn = r\connect('localhost');
r\db('bug_report')->table('literal')->get('fluffy')->update(array('attributes'=>array('colors'=>array('white'=>r\literal()))))->run($conn);
```
Returns error:
```
PHP Warning:  Missing argument 1 for r\literal(), called in literal.php on line 5 and defined in rdb/global.php on line 114
PHP Notice:  Undefined variable: value in rdb/global.php on line 115
```
Literal should be allowed to be called without arg.

r\literal(''), r\literal(null) and r\literal(array()) are not acceptable replacements, they do not return the same result that r\literal() should. They do some pretty odd things with the data though but I have not had time to explore how data explorer acts in these cases.

Expected Result:
attributes.colors.white is removed from Fluffy the cat.

Actual Result:
Error about literal missing argument 1

**Comment by danielmewes** [comment]
Thanks for the great report. I will look into it.

**Comment by danielmewes** [comment]
Merged a fix into `dev`. Will be released in the next version of PHP-RQL.
