### ISSUE TITLE
Proper usage of Map

### ISSUE THREAD

**Issue by acasanova** [danielmewes/php-rql#81]
I'm trying to run map to get an object that looks like the following

The query in js
````
r.db('accounts_archive').table('cancelled_accounts').
filter(function (doc){
return doc('user')('login').match('abc').not()
.and(doc('user')('login').match('demosite').not())
}).map(function(val){  
  return {"site_id": val('id'), "login" : val('user')('login'), 'member_since' : val('user')('created_at')}; 
})
````

My Attempt in php
````
$tmpCancelledAccounts = r\db('accounts_archive')			
			->table('cancelled_accounts')
			->filter(function($row){
				$r = $row->pluck(array('user'=>'login'))->coerceTo('string')->match('abc')->eq(null)
				->rAnd(
					$row->pluck(array('user'=>'login'))->coerceTo('string')->match('demosite')->eq(null)
					);
				return $r;
			})
			->map(function($row){
				$login = $row->pluck(array('user'=>'login'))->coerceTo('object');
				return array('login' => $login );
			})
			->run($this->conn)->toNative();
	
````

However, I get the following document when I the php version of the code
````
[
	{
		"login": {
			"user": {
				"login": "a@mac.com"
			}
		}
	},
	{
		"login": {
			"user": {
				"login": "d@mac.com"
			}
		}
	}
]
````

How do I get `"login":"d@mac.com"` instead of the embedded user document.
I tried doing coerceTo('string') but I get the object as a string not just the login value as a string.
Thanks in advanced

**Comment by danielmewes** [comment]
Hi @acasanova, in PHP, you cannot chain two field selections with the usual syntax (this is a language limitation). So you cannot write `doc('user')('login')` directly as you've probably noticed. However there is a replacement `getField` which you can use to get a field. Sop in PHP, you can write this as `doc('user')->getField('login')` or even `doc->getField('user')->getField('login')`.

Your JS query in PHP would hence become:
```php
r\db('accounts_archive')->table('cancelled_accounts')
->filter(function ($doc){
return $doc('user')->getField('login')->match('abc')->eq(null)
->rAnd($doc('user')->getField('login')->match('demosite')->eq(null));
})->map(function($val){  
  return array("site_id" => $val('id'), "login" => $val('user')->getField('login'), 'member_since' => $val('user')->getField('created_at')); 
})
```
(I also changed `match(...)->not()` to `match(...)->eq(null)` which I assume is what you meant)
