### ISSUE TITLE
Class already declared: r\Changes

### ISSUE THREAD

**Issue by acasanova** [danielmewes/php-rql#85]
I'm getting `Class already declared: r\Changes` exception. I see the Changes class is in rdb/queries/control.php on line 158 and rdb/queries/tables on line 133. Not sure exactly how to remediate this. 
I'm including the library like so `require_once(path("app") . "libraries/php-rql/rdb/rdb.php" );` in a laravel application.

**Comment by danielmewes** [comment]
Could it be that you have an old version of some driver files?
In `master` and `1.16.0` `r\Changes` should only be in `control.php`, not in `tables.php` (see https://github.com/danielmewes/php-rql/blob/1.16.0/src/rdb/queries/tables.php )

**Comment by acasanova** [comment]
You are right. Sorry about that..long week :)
