### ISSUE TITLE
Array to string conversion - hhvm

### ISSUE THREAD

**Issue by acasanova** [danielmewes/php-rql#86]
I have recently been using hhvm and I've been getting a error which causes hhvm to seg fault. I posted an issue in the project. Here's a link to the other post https://github.com/facebook/hhvm/issues/5158. Would you mind taking a look at the post to see if this is an error on my part or not?

It segfaults at the following line of code
https://github.com/danielmewes/php-rql/blob/1.15.0/src/rdb/function.php#L79

This is a dump of `$f` and `$reflection` objects right before line 79 respectively.

````
object(Closure$Services\Reporting::getCancelledUserCount;1080389369)#126 (1) { ["parameter"]=> array(1) { ["$row"]=> string(10) "" } }
````

````
object(ReflectionFunction)#129 (3) { ["name"]=> string(18) "Services\{closure}" ["closure":"ReflectionFunction":private]=> object(Closure$Services\Reporting::getCancelledUserCount;1080389369)#126 (1) { ["parameter"]=> array(1) { ["$row"]=> string(10) "" } } ["params":"ReflectionFunctionAbstract":private]=> array(1) { [0]=> object(ReflectionParameter)#130 (2) { ["info"]=> array(9) { ["index"]=> int(0) ["name"]=> string(3) "row" ["type"]=> string(0) "" ["type_hint"]=> string(0) "" ["function"]=> string(8) "__invoke" ["class"]=> string(60) "Closure$Services\Reporting::getCancelledUserCount;1080389369" ["nullable"]=> bool(true) ["attributes"]=> array(0) { } ["is_optional"]=> bool(false) } ["name"]=> string(3) "row" } } }
````

Sorry, I do not know which version of the code is currently being used. I suspect an older version than 1.15 since 1.13 is used in production.

FYI
I didn't have this issue prior to migrating to hhvm. Any suggestions would be helpful though

**Comment by acasanova** [comment]
I updated the https://github.com/facebook/hhvm/issues/5158 issue. Seems to be more of an hhvm issue. Sorry for the confusion.

**Comment by danielmewes** [comment]
Interesting, happy to see HHVM people are looking into it.
