### ISSUE TITLE
Question about orderBy

### ISSUE THREAD

**Issue by jamescostian** [danielmewes/php-rql#96]
A query like this returns a cursor:
```php
r\table( 'someTable' )->filter( array( 'something' => true ) )->run( $conn );
```

However, if you add `orderBy` like so:
```php
r\table( 'someTable' )->filter( array( 'something' => true ) )->orderBy( 'name' )->run( $conn );
```

Instead of getting a cursor, you get an array. This can be confusing. If you wrote the first query and then used `->toArray()` on it, but later added an `->orderBy()` then all of a sudden your code wouldn't work - you would need to remove the `->toArray()`.

What I'm wondering is whether or not this behavior is expected, and if so, what is the rationale behind it? I noticed that the same is true for the JS driver, so I'm not sure if this is the place to ask...

**Comment by danielmewes** [comment]
Hi @jamescostian, see this answer to a similar question on the main RethinkDB tracker: https://github.com/rethinkdb/rethinkdb/issues/4530#issuecomment-120559659
